stages:
  data_ingestion:
    cmd: python Music_Generation/Src/Pipelines/stage_01_data_ingestion.py
    deps:
      - Music_Generation/Src/Pipelines/stage_01_data_ingestion.py
  
  
  data_validation:
    cmd: python Music_Generation/Src/Pipelines/stage_02_data_validation.py
    deps:
      - Music_Generation/Src/Pipelines/stage_02_data_validation.py
      - Music_Generation/Config.yaml
      - Music_Generation/Params.yaml
    params:
      - Music_Generation/Params.yaml:
        - Data_Validation
        
      
  data_preparation:
    cmd: python Music_Generation/Src/Pipelines/stage_03_data_preparation.py
    deps:
      - Music_Generation/Src/Pipelines/stage_03_data_preparation.py
      - Artifacts/train
      - Artifacts/test
      - Artifacts/validation
      - Music_Generation/Config.yaml
      - Music_Generation/Params.yaml 
    params:
      - Music_Generation/Params.yaml:
        - Data_Preparation
    
      
  model_architecture_development:
    cmd : python Music_Generation/Src/Pipelines/stage_04_model_architecture_development.py
    deps:
      - Music_Generation/Src/Pipelines/stage_04_model_architecture_development.py
      - Music_Generation/Params.yaml 
    params:
      - Music_Generation/Params.yaml:
        - Model_config
          

  model_training:
    cmd : python Music_Generation/Src/Pipelines/stage_05_model_training.py
    deps:
      - Music_Generation/Src/Pipelines/stage_05_model_training.py 
      - Artifacts/Pickle/train
      - Artifacts/Pickle/test
      - Artifacts/Pickle/validation
      - Artifacts/Pickle/Architecture      
      - Music_Generation/Config.yaml
      - Music_Generation/Params.yaml
    params:
      - Music_Generation/Params.yaml:
        - Model_Training
         

  model_testing:
    cmd : python Music_Generation/Src/Pipelines/stage_06_model_testing.py
    deps:
      - Music_Generation/Src/Pipelines/stage_06_model_testing.py
      - Artifacts/Best_Model/best_model.h5
      - Music_Generation/Config.yaml
      - Music_Generation/Params.yaml
    params:
      - Music_Generation/Params.yaml:
        - Model_Testing
   


    