Data_Validation:
  SOURCE_MUSIC_DIRECTORY : "Artifacts/Dataset/Mix Music"
  TRAIN_MUSIC_DIRECTORY : "Artifacts/train/Mix Music"
  VALIDATION_MUSIC_DIRECTORY : "Artifacts/validation/Mix Music"
  TEST_MUSIC_DIRECTORY : "Artifacts/test/Mix Music"

Data_Preparation:
  TRAIN_MUSIC_DIRECTORY : "Artifacts/train/Mix Music"
  VALIDATION_MUSIC_DIRECTORY : "Artifacts/validation/Mix Music"
  TEST_MUSIC_DIRECTORY : "Artifacts/test/Mix Music"

Model_Callbacks:
  SAVE_BEST_MODEL_PATH : "Artifacts/best_model.h5"

Model_Testing:
  BEST_MODEL_PATH : "Artifacts/best_model.h5"
  TESTING_FILE_PATH : "Artifacts/test/Mix Music/abstract-future-bass-162604.mp3"
  


  